# Generated by Django 6.0.6 on 2026-06-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
