# Generated by Django 6.0.6 on 2026-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_pendingcheckout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='product_images/default.jpg', upload_to='product_images/'),
            preserve_default=False,
        ),
    ]
