# Generated by Django 6.0.6 on 2026-06-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_productimage_image_url_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingcheckout',
            name='address_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
