# Generated by Django 6.0.6 on 2026-06-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerprofile',
            name='profile_photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_photos/'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_photos/'),
        ),
    ]
