# Generated by Django 6.0.6 on 2026-06-26 10:11

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_consumerprofile_profile_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='area',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='instructions',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='landmark',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
    ]
