# Generated by Django 6.0.6 on 2026-06-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_deliveryaddress_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
