# Generated by Django 6.0.6 on 2026-06-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_farmerprofile_terms_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerprofile',
            name='profile_photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='consumer_photos/'),
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='consumer_photos/'),
        ),
    ]
