# Generated by Django 6.0.6 on 2026-06-26 10:07

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='consumer_phone_at_order',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
