# Generated by Django 6.0.6 on 2026-06-26 10:09

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_consumer_phone_at_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='payout',
            name='phone_number',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
