# Generated by Django 6.0.6 on 2026-06-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_mpesapayment_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='consumer_cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
